// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtkBoEk1il4SqYsPSZZO9rNk3dpuICj8',
    appId: '1:571254080057:web:a75a4e9bbbfb74c0c743e8',
    messagingSenderId: '571254080057',
    projectId: 'museum-app-8dd4b',
    authDomain: 'museum-app-8dd4b.firebaseapp.com',
    storageBucket: 'museum-app-8dd4b.firebasestorage.app',
    measurementId: 'G-TKF8HPM5JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10sTrdTpwEcvO_y3dXqqnfdNQoNGbH3k',
    appId: '1:571254080057:android:ed8c94ede136e534c743e8',
    messagingSenderId: '571254080057',
    projectId: 'museum-app-8dd4b',
    storageBucket: 'museum-app-8dd4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZRS-urDHKcvWMGQiSg_r8_jtvfIIXOFM',
    appId: '1:571254080057:ios:e8da9bfc9367a7e0c743e8',
    messagingSenderId: '571254080057',
    projectId: 'museum-app-8dd4b',
    storageBucket: 'museum-app-8dd4b.firebasestorage.app',
    iosBundleId: 'com.example.museumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZRS-urDHKcvWMGQiSg_r8_jtvfIIXOFM',
    appId: '1:571254080057:ios:e8da9bfc9367a7e0c743e8',
    messagingSenderId: '571254080057',
    projectId: 'museum-app-8dd4b',
    storageBucket: 'museum-app-8dd4b.firebasestorage.app',
    iosBundleId: 'com.example.museumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtkBoEk1il4SqYsPSZZO9rNk3dpuICj8',
    appId: '1:571254080057:web:3734a07bef57dd62c743e8',
    messagingSenderId: '571254080057',
    projectId: 'museum-app-8dd4b',
    authDomain: 'museum-app-8dd4b.firebaseapp.com',
    storageBucket: 'museum-app-8dd4b.firebasestorage.app',
    measurementId: 'G-DVKX11KBZ3',
  );
}
